# Site settings
title:
email:
description:
baseurl:
url:
twitter_username:
github_username:

# Build settings
markdown: kramdown
exclude: [mockup, repository, README.md, CHANGELOG.md, MILESTONES.md, STRUCTURE.md, TREE.md, LICENSE.md]
