# Site settings
title: tumbles.
email:
description: > # tumblr-like blog, based on Jekyll
baseurl:
url:
twitter_username:
github_username:

# Build settings
markdown: kramdown
exclude: [mockup, repository, README.md, CHANGELOG.md, MILESTONES.md, STRUCTURE.md, TREE.md, LICENSE.md]
